<?php

class Config {

	/**
	 * Array containing known html colors (and their hex values)
	 * (found at http://stackoverflow.com/questions/2553566/how-to-convert-a-string-color-to-its-hex-code-or-rgb-value)
	 * @var array 
	 */
	const HtmlColors = array(
		'aliceblue' => 'F0F8FF', 'antiquewhite' => 'FAEBD7', 'aqua' => '00FFFF', 'aquamarine' => '7FFFD4', 'azure' => 'F0FFFF',
		'beige' => 'F5F5DC', 'bisque' => 'FFE4C4', 'black' => '000000', 'blanchedalmond ' => 'FFEBCD', 'blue' => '0000FF',
		'blueviolet' => '8A2BE2', 'brown' => 'A52A2A', 'burlywood' => 'DEB887', 'cadetblue' => '5F9EA0', 'chartreuse' => '7FFF00',
		'chocolate' => 'D2691E', 'coral' => 'FF7F50', 'cornflowerblue' => '6495ED', 'cornsilk' => 'FFF8DC', 'crimson' => 'DC143C',
		'cyan' => '00FFFF', 'darkblue' => '00008B', 'darkcyan' => '008B8B', 'darkgoldenrod' => 'B8860B', 'darkgray' => 'A9A9A9',
		'darkgreen' => '006400', 'darkgrey' => 'A9A9A9', 'darkkhaki' => 'BDB76B', 'darkmagenta' => '8B008B', 'darkolivegreen' => '556B2F',
		'darkorange' => 'FF8C00', 'darkorchid' => '9932CC', 'darkred' => '8B0000', 'darksalmon' => 'E9967A', 'darkseagreen' => '8FBC8F',
		'darkslateblue' => '483D8B', 'darkslategray' => '2F4F4F', 'darkslategrey' => '2F4F4F', 'darkturquoise' => '00CED1', 'darkviolet' => '9400D3',
		'deeppink' => 'FF1493', 'deepskyblue' => '00BFFF', 'dimgray' => '696969', 'dimgrey' => '696969', 'dodgerblue' => '1E90FF',
		'firebrick' => 'B22222', 'floralwhite' => 'FFFAF0', 'forestgreen' => '228B22', 'fuchsia' => 'FF00FF', 'gainsboro' => 'DCDCDC',
		'ghostwhite' => 'F8F8FF', 'gold' => 'FFD700', 'goldenrod' => 'DAA520', 'gray' => '808080', 'green' => '008000',
		'greenyellow' => 'ADFF2F', 'grey' => '808080', 'honeydew' => 'F0FFF0', 'hotpink' => 'FF69B4', 'indianred' => 'CD5C5C',
		'indigo' => '4B0082', 'ivory' => 'FFFFF0', 'khaki' => 'F0E68C', 'lavender' => 'E6E6FA', 'lavenderblush' => 'FFF0F5',
		'lawngreen' => '7CFC00', 'lemonchiffon' => 'FFFACD', 'lightblue' => 'ADD8E6', 'lightcoral' => 'F08080', 'lightcyan' => 'E0FFFF',
		'lightgoldenrodyellow' => 'FAFAD2', 'lightgray' => 'D3D3D3', 'lightgreen' => '90EE90', 'lightgrey' => 'D3D3D3', 'lightpink' => 'FFB6C1',
		'lightsalmon' => 'FFA07A', 'lightseagreen' => '20B2AA', 'lightskyblue' => '87CEFA', 'lightslategray' => '778899', 'lightslategrey' => '778899',
		'lightsteelblue' => 'B0C4DE', 'lightyellow' => 'FFFFE0', 'lime' => '00FF00', 'limegreen' => '32CD32', 'linen' => 'FAF0E6',
		'magenta' => 'FF00FF', 'maroon' => '800000', 'mediumaquamarine' => '66CDAA', 'mediumblue' => '0000CD', 'mediumorchid' => 'BA55D3',
		'mediumpurple' => '9370D0', 'mediumseagreen' => '3CB371', 'mediumslateblue' => '7B68EE', 'mediumspringgreen' => '00FA9A', 'mediumturquoise' => '48D1CC',
		'mediumvioletred' => 'C71585', 'midnightblue' => '191970', 'mintcream' => 'F5FFFA', 'mistyrose' => 'FFE4E1', 'moccasin' => 'FFE4B5',
		'navajowhite' => 'FFDEAD', 'navy' => '000080', 'oldlace' => 'FDF5E6', 'olive' => '808000', 'olivedrab' => '6B8E23',
		'orange' => 'FFA500', 'orangered' => 'FF4500', 'orchid' => 'DA70D6', 'palegoldenrod' => 'EEE8AA', 'palegreen' => '98FB98',
		'paleturquoise' => 'AFEEEE', 'palevioletred' => 'DB7093', 'papayawhip' => 'FFEFD5', 'peachpuff' => 'FFDAB9', 'peru' => 'CD853F',
		'pink' => 'FFC0CB', 'plum' => 'DDA0DD', 'powderblue' => 'B0E0E6', 'purple' => '800080', 'red' => 'FF0000',
		'rosybrown' => 'BC8F8F', 'royalblue' => '4169E1', 'saddlebrown' => '8B4513', 'salmon' => 'FA8072', 'sandybrown' => 'F4A460',
		'seagreen' => '2E8B57', 'seashell' => 'FFF5EE', 'sienna' => 'A0522D', 'silver' => 'C0C0C0', 'skyblue' => '87CEEB',
		'slateblue' => '6A5ACD', 'slategray' => '708090', 'slategrey' => '708090', 'snow' => 'FFFAFA', 'springgreen' => '00FF7F',
		'steelblue' => '4682B4', 'tan' => 'D2B48C', 'teal' => '008080', 'thistle' => 'D8BFD8', 'tomato' => 'FF6347',
		'turquoise' => '40E0D0', 'violet' => 'EE82EE', 'wheat' => 'F5DEB3', 'white' => 'FFFFFF', 'whitesmoke' => 'F5F5F5',
		'yellow' => 'FFFF00', 'yellowgreen' => '9ACD32'
	);

	/**
	 * Array containing known inline pictures
	 * @var array 
	 */
	const SmartvisuInlinePictures = array(
		'arrow-l', 'arrow-r', 'arrow-u', 'arrow-d', 'delete', 'plus', 'minus', 'check', 'gear', 'refresh', 'forward', 'back',
		'grid', 'star', 'alert', 'info', 'home', 'search'
	);

	/**
	 * Array containing known button types
	 * @var array 
	 */
	const SmartvisuButtonTypes = array('micro', 'mini', 'midi');

	/**
	 * Configuration array for dynamic icon widget
	 */
	const IconWidgetConfiguration = array(
		0 => array('type' => 'id'),
		1 => array('type' => 'item'),
		2 => array('type' => 'item'),
		3 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
		4 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
	);

	/**
	 * Array containing parameter information for known global widgeds
	 * @var array
	 */
	const SmartvisuDefaultWidgets = array(
		'basic.button' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'text', 'optional' => TRUE, 'default' => ''),
			3 => array('type' => 'image', 'optional' => TRUE),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '1'),
			5 => array('type' => 'type', 'optional' => TRUE, 'default' => 'mini'),
			6 => array('type' => 'color', 'optional' => TRUE, 'default' => 'icon0'),
		),
		'basic.checkbox' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'text'),
		),
		'basic.colordisc' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item'),
			3 => array('type' => 'item'),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			5 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			6 => array('type' => 'value', 'optional' => TRUE),
			7 => array('type' => 'value', 'optional' => TRUE, 'default' => '10'),
		),
		'basic.dual' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'image', 'optional' => TRUE),
			3 => array('type' => 'image', 'optional' => TRUE),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '1'),
			5 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			6 => array('type' => 'type', 'optional' => TRUE, 'default' => 'mini'),
			7 => array('type' => 'color', 'optional' => TRUE, 'default' => 'icon1'),
			8 => array('type' => 'color', 'optional' => TRUE, 'default' => 'icon0'),
		),
		'basic.flip' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'text', 'optional' => TRUE, 'default' => 'On'),
			3 => array('type' => 'text', 'optional' => TRUE, 'default' => 'Off'),
		),
		'basic.float' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'text', 'optional' => TRUE),
			3 => array('type' => 'text', 'optional' => TRUE, 'default' => 'span'),
		),
		'basic.formula' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item', 'array_form' => 'may'),
			2 => array('type' => 'text', 'optional' => TRUE),
			3 => array('type' => 'text', 'optional' => TRUE, 'default' => 'SUM(VAR)'),
		),
		'basic.glue' => array(
			0 => array('type' => 'id', 'unique' => FALSE),
			1 => array('type' => 'id', 'unique' => FALSE),
		),
		'basic.multistate' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'value', 'array_form' => 'must'),
			3 => array('type' => 'image', 'array_form' => 'must'),
			4 => array('type' => 'type', 'optional' => TRUE, 'default' => 'Off'),
		),
		'basic.rgb' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item'),
			3 => array('type' => 'item'),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			5 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			6 => array('type' => 'value', 'optional' => TRUE),
			7 => array('type' => 'value', 'optional' => TRUE, 'default' => '10'),
		),
		'basic.shifter' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item', 'optional' => TRUE),
			2 => array('type' => 'item'),
			3 => array('type' => 'iconseries', 'optional' => TRUE, 'default' => 'light_light_dim_00.svg'),
			4 => array('type' => 'image', 'optional' => TRUE),
			5 => array('type' => 'value', 'optional' => TRUE),
			6 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
		),
		'basic.shutter' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item', 'optional' => TRUE),
			3 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			5 => array('type' => 'value', 'optional' => TRUE, 'default' => '5'),
			6 => array('type' => 'text', 'optional' => TRUE, 'default' => 'half', 'valid_values' => array('half', 'full')),
		),
		'basic.slider' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			3 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '5'),
			5 => array('type' => 'text', 'optional' => TRUE, 'valid_values' => array('none', 'vertical', 'bottomup', 'semicircle')),
		),
		'basic.switch' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'image', 'optional' => TRUE),
			3 => array('type' => 'image', 'optional' => TRUE),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '1'),
			5 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			6 => array('type' => 'color', 'optional' => TRUE, 'default' => 'icon1'),
			7 => array('type' => 'color', 'optional' => TRUE, 'default' => 'icon0'),
		),
		'basic.symbol' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item', 'array_form' => 'may'),
			2 => array('type' => 'text', 'optional' => TRUE),
			3 => array('type' => 'image', 'optional' => TRUE),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '1'),
			5 => array('type' => 'text', 'optional' => TRUE, 'default' => 'or', 'valid_values' => array('or', 'and')),
			6 => array('type' => 'color', 'optional' => TRUE, 'default' => 'icon0'),
		),
		'basic.tank' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			3 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '5'),
			5 => array('type' => 'text', 'optional' => TRUE, 'default' => 'none', 'valid_values' => array('none', 'cylinder', 'water', 'pallets')),
			6 => array('type' => 'color', 'optional' => TRUE, 'default' => 'grey'),
		),
		'basic.text' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'text', 'optional' => TRUE),
			3 => array('type' => 'text', 'optional' => TRUE),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '1'),
			5 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
		),
		'basic.trigger' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'text', 'optional' => TRUE),
			3 => array('type' => 'image', 'optional' => TRUE),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '1'),
			5 => array('type' => 'type', 'optional' => TRUE, 'default' => 'mini'),
		),
		'basic.value' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'text', 'optional' => TRUE),
			3 => array('type' => 'text', 'optional' => TRUE, 'default' => 'span'),
		),
		'calendar.list' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text', 'optional' => TRUE),
			2 => array('type' => 'value'),
			3 => array('type' => 'color', 'optional' => TRUE, 'default' => 'grey'),
			4 => array('type' => 'time', 'optional' => TRUE, 'default' => '1h'),
		),
		'clock.digiclock' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text', 'optional' => TRUE),
		),
		'clock.iconclock' => array(
			0 => array('type' => 'id'),
		),
		'clock.miniclock' => array(
			0 => array('type' => 'id'),
		),
		'device.blind' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text', 'optional' => TRUE),
			2 => array('type' => 'item'),
			3 => array('type' => 'item', 'optional' => TRUE),
			4 => array('type' => 'item'),
			5 => array('type' => 'item', 'optional' => TRUE),
			6 => array('type' => 'item', 'optional' => TRUE),
			7 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			8 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			9 => array('type' => 'value', 'optional' => TRUE, 'default' => '5'),
		),
		'device.codepad' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text', 'optional' => TRUE),
			2 => array('type' => 'text', 'optional' => TRUE),
			3 => array('type' => 'value', 'optional' => TRUE, 'default' => '10'),
		),
		'device.dimmer' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'item'),
			3 => array('type' => 'item'),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			5 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			6 => array('type' => 'value', 'optional' => TRUE, 'default' => '5'),
		),
		'device.rtr' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'item'),
			3 => array('type' => 'item'),
			4 => array('type' => 'item'),
			5 => array('type' => 'item'),
			6 => array('type' => 'item'),
			7 => array('type' => 'item'),
			8 => array('type' => 'item', 'optional' => TRUE),
			9 => array('type' => 'value', 'optional' => TRUE, 'default' => '0.5'),
		),
		'device.shutter' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'item'),
			3 => array('type' => 'item', 'optional' => TRUE),
			4 => array('type' => 'item'),
			5 => array('type' => 'item', 'optional' => TRUE),
			6 => array('type' => 'item', 'optional' => TRUE),
			7 => array('type' => 'item', 'optional' => TRUE),
			8 => array('type' => 'value', 'optional' => TRUE, 'default' => '0'),
			9 => array('type' => 'value', 'optional' => TRUE, 'default' => '255'),
			10 => array('type' => 'value', 'optional' => TRUE, 'default' => '5'),
			11 => array('type' => 'text', 'optional' => TRUE, 'default' => 'half', 'valid_values' => array('half', 'full')),
		),
		'icon.arrow' => IconWidgetConfiguration,
		'icon.battery' => IconWidgetConfiguration,
		'icon.blade' => IconWidgetConfiguration,
		'icon.blade2' => IconWidgetConfiguration,
		'icon.blade_z' => IconWidgetConfiguration,
		'icon.blade_arc' => IconWidgetConfiguration,
		'icon.clock' => IconWidgetConfiguration,
		'icon.compas' => IconWidgetConfiguration,
		'icon.graph' => IconWidgetConfiguration,
		'icon.light' => IconWidgetConfiguration,
		'icon.meter' => IconWidgetConfiguration,
		'icon.shutter' => IconWidgetConfiguration,
		'icon.ventilation' => IconWidgetConfiguration,
		'icon.volume' => IconWidgetConfiguration,
		'icon.windmill' => IconWidgetConfiguration,
		'icon.windrose' => IconWidgetConfiguration,
		'icon.windsock' => IconWidgetConfiguration,
		'icon.zenith' => IconWidgetConfiguration,
		'phone.list' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'value', 'optional' => TRUE, 'default' => '10'),
			3 => array('type' => 'time', 'optional' => TRUE, 'default' => '1h'),
		),
		'phone.missedlist' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'value', 'optional' => TRUE, 'default' => '10'),
			3 => array('type' => 'time', 'optional' => TRUE, 'default' => '1h'),
		),
		'plot.comfortchart' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item'),
		),
		'plot.minmaxavg' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'time', 'optional' => TRUE, 'default' => '1h'),
			3 => array('type' => 'time', 'optional' => TRUE, 'default' => 'now'),
			4 => array('type' => 'value', 'optional' => TRUE),
			5 => array('type' => 'value', 'optional' => TRUE),
			6 => array('type' => 'text', 'optional' => TRUE),
			7 => array('type' => 'value', 'optional' => TRUE),
			8 => array('type' => 'value', 'optional' => TRUE, 'default' => '100'),
		),
		'plot.multiaxis' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item', 'array_form' => 'may'),
			2 => array('type' => 'text', 'valid_values' => array('avg', 'sum', 'min', 'max')),
			3 => array('type' => 'time', 'optional' => TRUE, 'default' => '1h'),
			4 => array('type' => 'time', 'optional' => TRUE, 'default' => 'now'),
			5 => array('type' => 'value', 'optional' => TRUE, 'array_form' => 'must'),
			6 => array('type' => 'value', 'optional' => TRUE, 'array_form' => 'must'),
			7 => array('type' => 'value', 'optional' => TRUE, 'default' => '100'),
			8 => array('type' => 'text', 'optional' => TRUE, 'array_form' => 'may'),
			9 => array('type' => 'color', 'optional' => TRUE, 'array_form' => 'may'),
			10 => array('type' => 'text', 'optional' => TRUE, 'default' => 'line', 'array_form' => 'may', 'valid_values' => array('line', 'stair', 'spline', 'area', 'areaspline', 'column')),
			11 => array('type' => 'text', 'optional' => TRUE, 'array_form' => 'may'),
			12 => array('type' => 'time', 'optional' => TRUE),
			13 => array('type' => 'value', 'optional' => TRUE, 'array_form' => 'may'),
			14 => array('type' => 'text', 'optional' => TRUE, 'valid_values' => array('0', '1')),
			15 => array('type' => 'color', 'optional' => TRUE),
		),
		'plot.period' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item', 'array_form' => 'may'),
			2 => array('type' => 'text', 'valid_values' => array('avg', 'sum', 'min', 'max')),
			3 => array('type' => 'time', 'optional' => TRUE, 'default' => '1h'),
			4 => array('type' => 'time', 'optional' => TRUE, 'default' => 'now'),
			5 => array('type' => 'value', 'optional' => TRUE),
			6 => array('type' => 'value', 'optional' => TRUE),
			7 => array('type' => 'value', 'optional' => TRUE, 'default' => '100'),
			8 => array('type' => 'text', 'optional' => TRUE, 'array_form' => 'may'),
			9 => array('type' => 'color', 'optional' => TRUE, 'array_form' => 'may'),
			10 => array('type' => 'text', 'optional' => TRUE, 'default' => 'line', 'array_form' => 'may', 'valid_values' => array('line', 'stair', 'spline', 'area', 'areaspline', 'column')),
			11 => array('type' => 'text', 'optional' => TRUE, 'array_form' => 'may'),
			12 => array('type' => 'time', 'optional' => TRUE),
		),
		'plot.rtr' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item'),
			3 => array('type' => 'item'),
			4 => array('type' => 'value', 'optional' => TRUE, 'default' => '100'),
		),
		'plot.temprose' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item', 'array_form' => 'may'),
			2 => array('type' => 'item', 'array_form' => 'may'),
			3 => array('type' => 'text', 'array_form' => 'may'),
		),
		'multimedia.image' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'image'),
			2 => array('type' => 'text', 'optional' => TRUE, 'default' => 'none', 'valid_values' => array('none', 'corner', 'corner-bottom')),
			3 => array('type' => 'time', 'optional' => TRUE, 'default' => '10i'),
		),
		'multimedia.music' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item', 'optional' => TRUE),
			3 => array('type' => 'item', 'optional' => TRUE),
			4 => array('type' => 'item'),
			5 => array('type' => 'item', 'optional' => TRUE),
			6 => array('type' => 'item', 'optional' => TRUE),
			7 => array('type' => 'item', 'optional' => TRUE),
			8 => array('type' => 'item', 'optional' => TRUE),
			9 => array('type' => 'item', 'optional' => TRUE),
			10 => array('type' => 'item', 'optional' => TRUE),
			11 => array('type' => 'item', 'optional' => TRUE),
		),
		'multimedia.slideshow' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'value', 'optional' => TRUE, 'default' => '2'),
		//3 => array('type' => 'item'),
		//4 => array('type' => 'item'),
		//5 => array('type' => 'item'),
		//6 => array('type' => 'item'),
		),
		'multimedia.station' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'image'),
			3 => array('type' => 'value', 'optional' => TRUE, 'default' => 1),
			4 => array('type' => 'type', 'optional' => TRUE, 'default' => 'mini'),
		),
		'status.collapse' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
		),
		'status.log' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'value', 'min' => 1, 'max' => 50),
		),
		'status.message' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item', 'optional' => TRUE),
			3 => array('type' => 'item'),
			4 => array('type' => 'text', 'optional' => TRUE),
			5 => array('type' => 'text', 'optional' => TRUE),
			6 => array('type' => 'text', 'optional' => TRUE, 'default' => 'info', 'valid_values' => array('info', 'error')),
		),
		'status.notify' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'item'),
			2 => array('type' => 'item', 'optional' => TRUE),
			3 => array('type' => 'text'),
			4 => array('type' => 'text'),
			5 => array('type' => 'text', 'optional' => TRUE),
			6 => array('type' => 'text', 'optional' => TRUE, 'default' => 'info', 'valid_values' => array('info', 'warning', 'error')),
		),
		'weather.current' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text', 'optional' => TRUE),
			2 => array('type' => 'time', 'optional' => TRUE, 'default' => '1h'),
		),
		'weather.forecast' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text', 'optional' => TRUE),
			2 => array('type' => 'value', 'optional' => TRUE, 'default' => '1'),
			3 => array('type' => 'time', 'optional' => TRUE, 'default' => '3h'),
		),
		'weather.forecastweek' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text', 'optional' => TRUE),
		),
		'weather.map' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'text', 'valid_values' => array('day', 'night', 'forecast', 'wind', 'europe')),
		),
		'weather.mapslides' => array(
			0 => array('type' => 'id'),
			1 => array('type' => 'text'),
			2 => array('type' => 'value', 'optional' => TRUE, 'default' => '2'),
		),
		'now|smartdate' => array(),
		'now|date' => array(),
		'lib.updatecheck' => array(),
		'appliance.iprouter' => array(),
	);

}
